baseURL = "https://funtechjunk.xyz/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Funtechjunk"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true

[Googleadsense]
# Adsclient = "ca-pub-3712482145314951"
# AdsinArticleSlot = "3712482145314951"


[author]
  name = "Sidhant Parab"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
 
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Blog."
  # bgImg = ""  


  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false 

  code_copy_button = true 
  
  
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/SiddhantParab8"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/_war.l.ock_"

  [[params.social]]
    name = "github"
    url = "https://github.com/warlock1999"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 20
